<?php
namespace frontend\controllers\base;
use yii\web\Controller;

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/11/1
 * Time: 13:45
 */
class BaseController extends Controller {

    public function beforeAction($action) {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}